//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudObserverLite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudObserverLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AC_OETags_js {
            get {
                object obj = ResourceManager.GetObject("AC_OETags_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] framework_4_5_0_17689_swz {
            get {
                object obj = ResourceManager.GetObject("framework_4_5_0_17689_swz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] history_history_css {
            get {
                object obj = ResourceManager.GetObject("history_history_css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] history_history_js {
            get {
                object obj = ResourceManager.GetObject("history_history_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] history_historyFrame_html {
            get {
                object obj = ResourceManager.GetObject("history_historyFrame_html", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;title&gt;Cloud Observer&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;body{padding: 20px;background-color: #FFF;font: 100.01% &quot;Trebuchet MS&quot;,Verdana,Arial,sans-serif}
        ///h1,h2,p{margin: 0 10px}
        ///h1{font-size: 250%;color: #FFF; text-shadow: 0px 1px 1px #000;}
        ///h2{font-size: 200%;color: #f0f0f0;padding-top: 0.3em}
        ///div#nifty{ margin: 0 10%;background: # [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index_html {
            get {
                return ResourceManager.GetString("index_html", resourceCulture);
            }
        }
        
        internal static byte[] osmf_1_0_0_16316_swz {
            get {
                object obj = ResourceManager.GetObject("osmf_1_0_0_16316_swz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt; 
        ///&lt;head&gt; 	
        ///&lt;script src=&quot;AC_OETags.js&quot; language=&quot;javascript&quot;&gt;&lt;/script&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./history/history.css&quot; /&gt;
        ///&lt;script src=&quot;./history/history.js&quot; language=&quot;javascript&quot;&gt;&lt;/script&gt;
        ///&lt;script language=&quot;JavaScript&quot; type=&quot;text/javascript&quot;&gt;
        ///var requiredMajorVersion = 10; var requiredMinorVersion = 0; var requiredRevision = 0;
        ///&lt;/script&gt;
        ///&lt;META HTTP-EQUIV=&quot;Pragma&quot; CONTENT=&quot;no-cache&quot;&gt;
        ///&lt;META HT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string player_html {
            get {
                return ResourceManager.GetString("player_html", resourceCulture);
            }
        }
        
        internal static byte[] player_swf {
            get {
                object obj = ResourceManager.GetObject("player_swf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] playerProductInstall_swf {
            get {
                object obj = ResourceManager.GetObject("playerProductInstall_swf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rpc_4_5_0_17689_swz {
            get {
                object obj = ResourceManager.GetObject("rpc_4_5_0_17689_swz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] spark_4_5_0_17689_swz {
            get {
                object obj = ResourceManager.GetObject("spark_4_5_0_17689_swz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sparkskins_4_5_0_17689_swz {
            get {
                object obj = ResourceManager.GetObject("sparkskins_4_5_0_17689_swz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] swfobject_js {
            get {
                object obj = ResourceManager.GetObject("swfobject_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] textLayout_2_0_0_139_swz {
            get {
                object obj = ResourceManager.GetObject("textLayout_2_0_0_139_swz", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
