//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4927
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudObserver.Services.StreamingService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StreamingServiceDiagnostics", Namespace="http://schemas.datacontract.org/2004/07/CloudObserver.Services.StreamingService")]
    public partial class StreamingServiceDiagnostics : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int bufferLengthField;
        
        private int bufferPositionField;
        
        private int lastReadPositionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bufferLength
        {
            get
            {
                return this.bufferLengthField;
            }
            set
            {
                this.bufferLengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bufferPosition
        {
            get
            {
                return this.bufferPositionField;
            }
            set
            {
                this.bufferPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lastReadPosition
        {
            get
            {
                return this.lastReadPositionField;
            }
            set
            {
                this.lastReadPositionField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStreamingService")]
public interface IStreamingService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/GetDiagnostics", ReplyAction="http://tempuri.org/IStreamingService/GetDiagnosticsResponse")]
    CloudObserver.Services.StreamingService.StreamingServiceDiagnostics GetDiagnostics();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/Read", ReplyAction="http://tempuri.org/IStreamingService/ReadResponse")]
    int Read(out byte[] buffer, int offset, int count, ref int position, bool synchronize);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/Write", ReplyAction="http://tempuri.org/IStreamingService/WriteResponse")]
    void Write(System.IO.MemoryStream dataStream);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamingService/Synchronize", ReplyAction="http://tempuri.org/IStreamingService/SynchronizeResponse")]
    int Synchronize();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IStreamingServiceChannel : IStreamingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class StreamingServiceClient : System.ServiceModel.ClientBase<IStreamingService>, IStreamingService
{
    
    public StreamingServiceClient()
    {
    }
    
    public StreamingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StreamingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StreamingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StreamingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CloudObserver.Services.StreamingService.StreamingServiceDiagnostics GetDiagnostics()
    {
        return base.Channel.GetDiagnostics();
    }
    
    public int Read(out byte[] buffer, int offset, int count, ref int position, bool synchronize)
    {
        return base.Channel.Read(out buffer, offset, count, ref position, synchronize);
    }
    
    public void Write(System.IO.MemoryStream dataStream)
    {
        base.Channel.Write(dataStream);
    }
    
    public int Synchronize()
    {
        return base.Channel.Synchronize();
    }
}