//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudObserverBroadcastTestFormApp.CloudObserverBroadcastService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudObserverBroadcastService.ICloudObserverBroadcastService")]
    public interface ICloudObserverBroadcastService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICloudObserverBroadcastService/bindMeToCamera", ReplyAction="http://tempuri.org/ICloudObserverBroadcastService/bindMeToCameraResponse")]
        void bindMeToCamera(int clientID, int cameraID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICloudObserverBroadcastService/setMeAsCamera", ReplyAction="http://tempuri.org/ICloudObserverBroadcastService/setMeAsCameraResponse")]
        void setMeAsCamera(int cameraID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICloudObserverBroadcastService/getNextFrame", ReplyAction="http://tempuri.org/ICloudObserverBroadcastService/getNextFrameResponse")]
        byte[] getNextFrame(int cameraID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICloudObserverBroadcastService/setNextFrame", ReplyAction="http://tempuri.org/ICloudObserverBroadcastService/setNextFrameResponse")]
        void setNextFrame(byte[] frame);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICloudObserverBroadcastServiceChannel : CloudObserverBroadcastTestFormApp.CloudObserverBroadcastService.ICloudObserverBroadcastService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CloudObserverBroadcastServiceClient : System.ServiceModel.ClientBase<CloudObserverBroadcastTestFormApp.CloudObserverBroadcastService.ICloudObserverBroadcastService>, CloudObserverBroadcastTestFormApp.CloudObserverBroadcastService.ICloudObserverBroadcastService {
        
        public CloudObserverBroadcastServiceClient() {
        }
        
        public CloudObserverBroadcastServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CloudObserverBroadcastServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CloudObserverBroadcastServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CloudObserverBroadcastServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void bindMeToCamera(int clientID, int cameraID) {
            base.Channel.bindMeToCamera(clientID, cameraID);
        }
        
        public void setMeAsCamera(int cameraID) {
            base.Channel.setMeAsCamera(cameraID);
        }
        
        public byte[] getNextFrame(int cameraID) {
            return base.Channel.getNextFrame(cameraID);
        }
        
        public void setNextFrame(byte[] frame) {
            base.Channel.setNextFrame(frame);
        }
    }
}
