start bin\SimplePolicyRetrieverServiceHoster.exe
start bin\SimpleServiceHoster.exe %cd%\bin\CloudObserverAccountsServiceLibrary.dll CloudObserverAccountsService
start bin\SimpleServiceHoster.exe %cd%\bin\CloudObserverAuthorizationServiceLibrary.dll CloudObserverAuthorizationService
start bin\SimpleServiceHoster.exe %cd%\bin\CloudObserverBroadcastServiceLibrary.dll CloudObserverBroadcastService
start bin\SimpleServiceHoster.exe %cd%\bin\CloudObserverStorageServiceLibrary.dll CloudObserverStorageService
start bin\SimpleServiceHoster.exe %cd%\bin\CloudObserverVirtualCamerasServiceLibrary.dll CloudObserverVirtualCamerasService
CloudObserverWebsite\Default.html