# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = bin/obj/Debug
  TARGETDIR  = bin/debug
  TARGET     = $(TARGETDIR)/CloudForeverWriter
  DEFINES   += -DMAC -DDEBUG
  INCLUDES  += -I/opt/local/include -I/usr/include -I/usr/local/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L/opt/local/lib -L/System/Libarary/Frameworks -L/Library/Frameworks -L/usr/lib -L/usr/local/lib
  LIBS      += -lavcodec -lavformat -lavutil -lswscale -lopencv_core -lopencv_highgui -lopencv_imgproc -framework Carbon -framework OpenAL -framework QuickTime -lboost_regex -lboost_system -lboost_thread
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = bin/obj/Release
  TARGETDIR  = bin/release
  TARGET     = $(TARGETDIR)/CloudForeverWriter
  DEFINES   += -DMAC -DNDEBUG
  INCLUDES  += -I/opt/local/include -I/usr/include -I/usr/local/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -Wl,-x -L/opt/local/lib -L/System/Libarary/Frameworks -L/Library/Frameworks -L/usr/lib -L/usr/local/lib
  LIBS      += -lavcodec -lavformat -lavutil -lswscale -lopencv_core -lopencv_highgui -lopencv_imgproc -framework Carbon -framework OpenAL -framework QuickTime -lboost_regex -lboost_system -lboost_thread
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug32)
  OBJDIR     = bin/obj/x32/Debug
  TARGETDIR  = bin/debug
  TARGET     = $(TARGETDIR)/CloudForeverWriter
  DEFINES   += -DMAC -DDEBUG
  INCLUDES  += -I/opt/local/include -I/usr/include -I/usr/local/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m32 -L/usr/lib32 -L/opt/local/lib -L/System/Libarary/Frameworks -L/Library/Frameworks -L/usr/lib -L/usr/local/lib
  LIBS      += -lavcodec -lavformat -lavutil -lswscale -lopencv_core -lopencv_highgui -lopencv_imgproc -framework Carbon -framework OpenAL -framework QuickTime -lboost_regex -lboost_system -lboost_thread
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR     = bin/obj/x32/Release
  TARGETDIR  = bin/release
  TARGET     = $(TARGETDIR)/CloudForeverWriter
  DEFINES   += -DMAC -DNDEBUG
  INCLUDES  += -I/opt/local/include -I/usr/include -I/usr/local/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -Wl,-x -m32 -L/usr/lib32 -L/opt/local/lib -L/System/Libarary/Frameworks -L/Library/Frameworks -L/usr/lib -L/usr/local/lib
  LIBS      += -lavcodec -lavformat -lavutil -lswscale -lopencv_core -lopencv_highgui -lopencv_imgproc -framework Carbon -framework OpenAL -framework QuickTime -lboost_regex -lboost_system -lboost_thread
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/CloudForeverWriter.o \
	$(OBJDIR)/CloudObserverVirtualWriter.o \
	$(OBJDIR)/list.o \
	$(OBJDIR)/LSD.o \
	$(OBJDIR)/VideoEncoder.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking CloudForeverWriter
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning CloudForeverWriter
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/CloudForeverWriter.o: ../../Code/CloudForeverWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CloudObserverVirtualWriter.o: ../../Code/CloudObserverVirtualWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/list.o: ../../Code/list.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LSD.o: ../../Code/LSD.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VideoEncoder.o: ../../Code/VideoEncoder.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
