//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace CloudObserverUserInterface.CloudObserverBroadcastServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService")]
    public interface ICloudObserverBroadcastService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICloudObserverBroadcastService/ReadFrame", ReplyAction="http://tempuri.org/ICloudObserverBroadcastService/ReadFrameResponse")]
        System.IAsyncResult BeginReadFrame(int cameraID, System.AsyncCallback callback, object asyncState);
        
        byte[] EndReadFrame(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICloudObserverBroadcastService/WriteFrame", ReplyAction="http://tempuri.org/ICloudObserverBroadcastService/WriteFrameResponse")]
        System.IAsyncResult BeginWriteFrame(int cameraID, byte[] frame, System.AsyncCallback callback, object asyncState);
        
        void EndWriteFrame(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICloudObserverBroadcastServiceChannel : CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ReadFrameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReadFrameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CloudObserverBroadcastServiceClient : System.ServiceModel.ClientBase<CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService>, CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService {
        
        private BeginOperationDelegate onBeginReadFrameDelegate;
        
        private EndOperationDelegate onEndReadFrameDelegate;
        
        private System.Threading.SendOrPostCallback onReadFrameCompletedDelegate;
        
        private BeginOperationDelegate onBeginWriteFrameDelegate;
        
        private EndOperationDelegate onEndWriteFrameDelegate;
        
        private System.Threading.SendOrPostCallback onWriteFrameCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public CloudObserverBroadcastServiceClient() {
        }
        
        public CloudObserverBroadcastServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CloudObserverBroadcastServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CloudObserverBroadcastServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CloudObserverBroadcastServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<ReadFrameCompletedEventArgs> ReadFrameCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> WriteFrameCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService.BeginReadFrame(int cameraID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReadFrame(cameraID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService.EndReadFrame(System.IAsyncResult result) {
            return base.Channel.EndReadFrame(result);
        }
        
        private System.IAsyncResult OnBeginReadFrame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int cameraID = ((int)(inValues[0]));
            return ((CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService)(this)).BeginReadFrame(cameraID, callback, asyncState);
        }
        
        private object[] OnEndReadFrame(System.IAsyncResult result) {
            byte[] retVal = ((CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService)(this)).EndReadFrame(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReadFrameCompleted(object state) {
            if ((this.ReadFrameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReadFrameCompleted(this, new ReadFrameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReadFrameAsync(int cameraID) {
            this.ReadFrameAsync(cameraID, null);
        }
        
        public void ReadFrameAsync(int cameraID, object userState) {
            if ((this.onBeginReadFrameDelegate == null)) {
                this.onBeginReadFrameDelegate = new BeginOperationDelegate(this.OnBeginReadFrame);
            }
            if ((this.onEndReadFrameDelegate == null)) {
                this.onEndReadFrameDelegate = new EndOperationDelegate(this.OnEndReadFrame);
            }
            if ((this.onReadFrameCompletedDelegate == null)) {
                this.onReadFrameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReadFrameCompleted);
            }
            base.InvokeAsync(this.onBeginReadFrameDelegate, new object[] {
                        cameraID}, this.onEndReadFrameDelegate, this.onReadFrameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService.BeginWriteFrame(int cameraID, byte[] frame, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginWriteFrame(cameraID, frame, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService.EndWriteFrame(System.IAsyncResult result) {
            base.Channel.EndWriteFrame(result);
        }
        
        private System.IAsyncResult OnBeginWriteFrame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int cameraID = ((int)(inValues[0]));
            byte[] frame = ((byte[])(inValues[1]));
            return ((CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService)(this)).BeginWriteFrame(cameraID, frame, callback, asyncState);
        }
        
        private object[] OnEndWriteFrame(System.IAsyncResult result) {
            ((CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService)(this)).EndWriteFrame(result);
            return null;
        }
        
        private void OnWriteFrameCompleted(object state) {
            if ((this.WriteFrameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WriteFrameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WriteFrameAsync(int cameraID, byte[] frame) {
            this.WriteFrameAsync(cameraID, frame, null);
        }
        
        public void WriteFrameAsync(int cameraID, byte[] frame, object userState) {
            if ((this.onBeginWriteFrameDelegate == null)) {
                this.onBeginWriteFrameDelegate = new BeginOperationDelegate(this.OnBeginWriteFrame);
            }
            if ((this.onEndWriteFrameDelegate == null)) {
                this.onEndWriteFrameDelegate = new EndOperationDelegate(this.OnEndWriteFrame);
            }
            if ((this.onWriteFrameCompletedDelegate == null)) {
                this.onWriteFrameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWriteFrameCompleted);
            }
            base.InvokeAsync(this.onBeginWriteFrameDelegate, new object[] {
                        cameraID,
                        frame}, this.onEndWriteFrameDelegate, this.onWriteFrameCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService CreateChannel() {
            return new CloudObserverBroadcastServiceClientChannel(this);
        }
        
        private class CloudObserverBroadcastServiceClientChannel : ChannelBase<CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService>, CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService {
            
            public CloudObserverBroadcastServiceClientChannel(System.ServiceModel.ClientBase<CloudObserverUserInterface.CloudObserverBroadcastServiceReference.ICloudObserverBroadcastService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginReadFrame(int cameraID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cameraID;
                System.IAsyncResult _result = base.BeginInvoke("ReadFrame", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndReadFrame(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("ReadFrame", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWriteFrame(int cameraID, byte[] frame, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = cameraID;
                _args[1] = frame;
                System.IAsyncResult _result = base.BeginInvoke("WriteFrame", _args, callback, asyncState);
                return _result;
            }
            
            public void EndWriteFrame(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("WriteFrame", _args, result);
            }
        }
    }
}
