//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4927
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "Silverlight", ConfigurationName = "IStreamingService", CallbackContract = typeof(IStreamingServiceCallback))]
public interface IStreamingService
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "Silverlight/IStreamingService/Send")]
    void Send(byte[] data);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "Silverlight/IStreamingService/SetSubscriptionResponse")]
    void SetSubscriptionResponse(byte[] response);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "Silverlight/IStreamingService/Subscribe")]
    void Subscribe(System.TimeSpan timeout);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "Silverlight/IStreamingService/Unsubscribe")]
    void Unsubscribe();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IStreamingServiceCallback
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "Silverlight/IStreamingService/DataCallback")]
    void DataCallback(byte[] data);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "Silverlight/IStreamingService/SubscriptionResponse")]
    void SubscriptionResponse(byte[] response);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IStreamingServiceChannel : IStreamingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class StreamingServiceClient : System.ServiceModel.DuplexClientBase<IStreamingService>, IStreamingService
{

    public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance) :
        base(callbackInstance)
    {
    }

    public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
        base(callbackInstance, endpointConfigurationName)
    {
    }

    public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, binding, remoteAddress)
    {
    }

    public void Send(byte[] data)
    {
        base.Channel.Send(data);
    }

    public void SetSubscriptionResponse(byte[] response)
    {
        base.Channel.SetSubscriptionResponse(response);
    }

    public void Subscribe(System.TimeSpan timeout)
    {
        base.Channel.Subscribe(timeout);
    }

    public void Unsubscribe()
    {
        base.Channel.Unsubscribe();
    }
}