//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4927
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IStreamingService")]
public interface IStreamingService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStreamingService/Read", ReplyAction = "http://tempuri.org/IStreamingService/ReadResponse")]
    int Read(out byte[] buffer, int count, ref int position, bool synchronize);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStreamingService/Write", ReplyAction = "http://tempuri.org/IStreamingService/WriteResponse")]
    void Write(byte[] data);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStreamingService/Synchronize", ReplyAction = "http://tempuri.org/IStreamingService/SynchronizeResponse")]
    int Synchronize();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IStreamingServiceChannel : IStreamingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class StreamingServiceClient : System.ServiceModel.ClientBase<IStreamingService>, IStreamingService
{

    public StreamingServiceClient()
    {
    }

    public StreamingServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public StreamingServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public StreamingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public StreamingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public int Read(out byte[] buffer, int count, ref int position, bool synchronize)
    {
        return base.Channel.Read(out buffer, count, ref position, synchronize);
    }

    public void Write(byte[] data)
    {
        base.Channel.Write(data);
    }

    public int Synchronize()
    {
        return base.Channel.Synchronize();
    }
}